---
title: "STA302"
output:
  pdf_document: default
  html_document: default
date: "2024-10-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading Data
```{r}

#install.packages('tidyverse')
library(tidyverse)

data <- read_csv("dating_data.csv")

names(data) <- gsub(" ", "_", names(data)) #Changes Spaces to Underlines: 

```

## Add Full names
```{r}

# Adds a new column with the full country name using case_when
data <- data %>%
  mutate(country_full = case_when(
    country == "CH" ~ "Switzerland",
    country == "CA" ~ "Canada",
    country == "DE" ~ "Germany",
    country == "FR" ~ "France",
    country == "US" ~ "United States of America",
    country == "AT" ~ "Austria",
    country == "CZ" ~ "Czech Republic",
    country == "JM" ~ "Jamaica",
    country == "SC" ~ "Seychelles",
    country == "LR" ~ "Liberia",
    country == "BA" ~ "Bosnia and Herzegovina",
    country == "IT" ~ "Italy",
    country == "LI" ~ "Liechtenstein",
    country == "ES" ~ "Spain",
    country == "NL" ~ "Netherlands",
    country == "LU" ~ "Luxembourg",
    country == "AU" ~ "Australia",
    country == "BR" ~ "Brazil",
    country == "RU" ~ "Russia",
    country == "ID" ~ "Indonesia",
    country == "TR" ~ "Turkey",
    country == "GB" ~ "United Kingdom",
    country == "BE" ~ "Belgium",
    country == "ET" ~ "Ethiopia",
    country == "HU" ~ "Hungary",
    country == "AR" ~ "Argentina",
    country == "PE" ~ "Peru",
    country == "UA" ~ "Ukraine",
    country == "IN" ~ "India",
    country == "RO" ~ "Romania",
    country == "PH" ~ "Philippines",
    country == "CF" ~ "Central African Republic",
    TRUE ~ NA_character_  # For any unmatched values, set to NA
  ))

```

## Add population
```{r}

# Adds a new column with the population of each country
data <- data %>%
  mutate(country_pop = case_when(
    country == "CH" ~ 8849850,
    country == "CA" ~ 40097760,
    country == "DE" ~ 84482270,
    country == "FR" ~ 68170230,
    country == "US" ~ 334914900,
    country == "AT" ~ 9132380,
    country == "CZ" ~ 10873690,
    country == "JM" ~ 2825540,
    country == "SC" ~ 119770,
    country == "LR" ~ 5418380,
    country == "BA" ~ 3210850,
    country == "IT" ~ 58761150,
    country == "LI" ~ 39580,
    country == "ES" ~ 48373340,
    country == "NL" ~ 17879490,
    country == "LU" ~ 668610,
    country == "AU" ~ 26638540,
    country == "BR" ~ 216422450,
    country == "RU" ~ 143826130,
    country == "ID" ~ 277534120,
    country == "TR" ~ 85326000,
    country == "GB" ~ 68350000,
    country == "BE" ~ 11822590,
    country == "ET" ~ 126527060,
    country == "HU" ~ 9589870,
    country == "AR" ~ 46654580,
    country == "PE" ~ 34352720,
    country == "UA" ~ 37000000,
    country == "IN" ~ 1428627660,
    country == "RO" ~ 19056120,
    country == "PH" ~ 117337370,
    country == "CF" ~ 5742310,
    TRUE ~ NA_real_  # For any unmatched values, set to NA
  ))

# Removes the outlier for count_kisses
data <- filter(data, counts_kisses != 9288)

write.csv(data, file = "cleaned_dating_data.csv", row.names = FALSE)

download.file("http://cleaned_dating_data.csv", destfile = )
```

## Summary Tables
```{r}
summary(data$counts_kisses)

summary(data$age)

summary(data$counts_pictures)

summary(data$counts_profileVisits)

summary(data$country_pop)

summary(data$genderLooking)
```

## Regression Model 1 & Residual Plots
```{r}

# MODEL ONE: Regression
model <- lm(counts_kisses ~ age + counts_pictures + counts_profileVisits + country_pop + genderLooking, data = data)

# RESIDUAL PLOTS 
par(mfrow = c(1, 3)) # Environment 2
# 1. Residual vs Fitted plot
x1 = fitted(model)
y1 = resid(model)
plot_model1 <- plot(x = x1, y = y1, xlab = "Fitted", ylab = "Residual", main = "Residual vs Fitted")

# 2. Residual vs Predictor: Age 
plot(y1 ~ data$age, main = "Residual vs Age", 
     xlab = "Age", ylab = "Residual")

# 3. Residual vs Predictor: counts_picture 
plot(y1 ~ data$counts_pictures, main = "Residual vs Number of Prictures", 
     xlab = "Number of Pictures", ylab = "Residual")

par(mfrow = c(1, 1))

par(mfrow = c(1, 2)) # Environment 2
# 4. Residual vs Predictor: country_pop 
plot(y1 ~ data$country_pop, main = "Residual vs Country Population", 
     xlab = "Country Population", ylab = "Residual")

# 5. Residual vs Predictor: counts_profileVisits 
plot(y1 ~ data$counts_profileVisits, main = "Residual vs Profile Visits", 
     xlab = "Profile Vists", ylab = "Residual")
par(mfrow = c(1, 1))

par(mfrow = c(1, 2)) # Environment 3
# 6. Residual vs Predictor: genderLooking
boxplot(y1 ~ data$genderLooking, main = "Residual vs Gender of Interest", 
     xlab = "Gender of Interest", ylab = "Residual", names = c('Female', 'Both', 'Male', 'None'))

# QQ-NORM PLOTS 
qqnorm_model1 <- qqnorm(y1, ylim = c(-1000, 1000))
qqline(y1)

par(mfrow = c(1, 1))

```

## Checking Two Conditions
```{r}
# Checking Assumption 1: Response vs Fitted
condition_1 <- plot(x = x1, y = data$counts_kisses, main = "Likes vs Fitted", xlab = "Fitted", ylab = "Likes", ylim = c(0, 3100))
abline(a=0, b=1, lty=2) # 45 degree line

# Checking Assumption 2: Pairwise Scatterplot
condition_2 <- pairs(data[, c("age", "counts_pictures", "counts_profileVisits", "country_pop")])
```




